# Generated by Django 5.2 on 2025-04-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='coordinates',
        ),
    ]
